# ------ root_path ------
root_path: ''


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [7, 3]
search_step: [200, 20]

init_beta: 1
init_alpha: 0.4

gpt3_prompt_file: './gpt_file/imagenet_prompt.json'

# ------ Basic Config ------
dataset: 'ImageNet'
shots: 4
clip_backbone: 'RN50'
dino_backbone: 'resnet50'

# ------ Dalle Dataset -----
dalle_dataset: 'dalle_imagenet'
dalle_shots: 8

lr: 0.001
augment_epoch: 1
train_epoch: 20
